version: "3"
services:
    buddy_connect:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      volumes:
        - ./:/app
        - /app/node_modules
    redis:
        image: redis
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - buddy_connect
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf